### ISSUE TITLE
iOS 9.0, 10.0 Support

### ISSUE THREAD

**Issue by wimbledon** [XQS6LB3A/lyrics-module#6]
Error Compiling for iOS 10.0, but module 'LyricsService' has a minimum deployment target of iOS 13.0: 
![image](https://user-images.githubusercontent.com/3291853/125166625-7b6ea880-e1d7-11eb-90ad-93df35521788.png)

**Comment by wimbledon** [comment]
I tried following https://github.com/cx-org/CXShim#can-i-use-other-open-source-combine by setting `export CX_COMBINE_IMPLEMENTATION=CombineX` but still getting the same error...

**Comment by wimbledon** [comment]
I also came across https://forums.swift.org/t/combine-backward-deployment-and-linux/37855

**Comment by wimbledon** [comment]
I was able to resolve the problem by running `open Package.swift`.
I also came across https://github.com/ddddxxx/LyricsKit/blob/master/OpenWithCombineX.command
Curious to know why `open Package.swift` is needed...

**Comment by ddddxxx** [comment]
> Curious to know why `open Package.swift` is needed...

Because [CXShim read env variable in Package.swift](https://github.com/cx-org/CXShim/blob/master/Package.swift#L87). The env variable must present when resolving package. If you're using Xcode, you need to launch Xcode with env variable. like this https://github.com/ddddxxx/LyricsX/blob/master/DevOpen and https://github.com/ddddxxx/LyricsKit/blob/master/OpenWithCombineX.command

**Comment by wimbledon** [comment]
Thank you!
